name: Tjek udløbsdatoer og send e-mail

on:
  schedule:
    - cron: '0 6 * * *'  # Kører hver dag kl. 08:00 dansk tid (UTC+2 i sommerperiode)
  workflow_dispatch:  # Tillader manuel kørsel

jobs:
  tjek-udloeb:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository content
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytz requests dropbox

    - name: Tjek udløb og send e-mail
      env:
        APP_KEY: ${{ secrets.APP_KEY }}
        APP_SECRET: ${{ secrets.APP_SECRET }}
        REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
        EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
        EMAIL_RECIPIENT: ${{ secrets.EMAIL_RECIPIENT }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      run: |
        python daily-email-report.py